// Generated by CoffeeScript 1.3.3
(function() {
  var Bubble;

  Zepto(function() {
    $('button#new_game').click(function() {
      return window.bubble = new Bubble($('#bubble'));
    });
    return $('button#new_game').trigger('click');
  });

  Bubble = (function() {

    function Bubble(element) {
      this.element = element;
      this.element.removeClass();
      this.element.removeAttr('style');
      this.element.show();
      $('#gameover').hide();
      this.available_height = $(window).height();
      this.available_width = $(window).width();
      this.center();
      this.size();
      this.scaler = 3;
      this.bindEvents();
    }

    Bubble.prototype.center = function() {
      this.element.css("position", "absolute");
      this.element.css("top", Math.max(0, ((this.available_height - this.element.height()) / 2) + window.pageYOffset) + "px");
      return this.element.css("left", Math.max(0, ((this.available_width - this.element.width()) / 2) + window.pageXOffset) + "px");
    };

    Bubble.prototype.size = function() {
      var size;
      size = this.available_width / 10;
      return this.element.width("" + size + "px").height("" + size + "px");
    };

    Bubble.prototype.randomSize = function() {
      return "" + (this.element.width() + (Math.random() * (this.element.width() / this.scaler))) + "px";
    };

    Bubble.prototype.gameDidFinish = function() {
      this.element.addClass('finished');
      this.element.unbind('click').unbind('doubleTap');
      return this.element.animate({
        opacity: 0
      }, 500, 'ease-in', function() {
        return $('#gameover').show();
      });
    };

    Bubble.prototype.didGameFinish = function() {
      if (this.element.width() > this.available_width) {
        return this.gameDidFinish();
      }
    };

    Bubble.prototype.expand = function() {
      var size;
      size = this.randomSize();
      this.element.width(size).height(size);
      this.center();
      return this.didGameFinish();
    };

    Bubble.prototype.bindEvents = function() {
      var _this = this;
      this.element.click(function() {
        return _this.expand();
      });
      return this.element.doubleTap(function() {
        return _this.expand();
      });
    };

    return Bubble;

  })();

}).call(this);
